# Use uma imagem base do Nginx
FROM nginx:alpine

# Copie os arquivos estáticos para o diretório de trabalho do Nginx
COPY . /usr/share/nginx/html

# Exponha a porta em que o Nginx está sendo executado
EXPOSE 80
